version: '3.8'
services:
  backend_app:
    container_name: backend_app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/frontend
    ports:
      - 8000:80
  db:
    container_name: db
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: visualsqleditor
      MARIADB_USER: wp
      MARIADB_PASSWORD: qwerty
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/frontend
    ports:
      - '9906:3306'
