version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: visualsqleditor
      MARIADB_USER: wp
      MARIADB_PASSWORD: qwerty
    ports:
      - '9906:3306'
